### ISSUE TITLE
解决 Nimble 无法发送 ACL 包的 bug

### ISSUE THREAD

**Issue by Jackistang** [Jackistang/HM#33]

**Comment by Jackistang** [comment]
694ea8337286db480ed776d7a2bf7c018a39c927 & 9a11fdd3633838823767a1708acc7b3deaf87b82

**Comment by Jackistang** [comment]
定位 bug 措施：
1. 实现 HCI log，并打印
2. 确定为什么接收到第一个 ACL 包后再发送 Command 接收 Event 会超时

**Comment by Jackistang** [comment]
5da819673b45e243ba9ee8a1bef15dffed53b381

**Comment by supperthomas** [comment]
qemu.

**Comment by Jackistang** [comment]
收包时用一个邮箱替换两个邮箱。

**Comment by Jackistang** [comment]
仔细阅读 ble_hs_hci.c 文件，找出现有实现方式的问题。

**Comment by Jackistang** [comment]
event enqueue 和 no enqueue 的区别。

**Comment by Jackistang** [comment]
Bug 现象：

建立连接时，NimBLE 发送 LE Read Remote Features Command，但是并没有立即收到 Command Status Event (LE Read Remote Features)，而是超时后才收到，但已经晚了。
![](https://user-images.githubusercontent.com/45490946/132113572-7edb2c23-4564-435f-968c-71a746f0d175.png)

**Comment by Jackistang** [comment]
Bug 解决：

NimBLE 将 HCI Event 分为两类，
- 一类是发送 HCI Command 后立即返回的 HCI Event（Command Complete 和 Command Status），NimBLE 发送 HCI Command 后调用函数 `ble_hs_hci_wait_for_ack()` 阻塞，直至有相应的 Event 返回。
- 另一类是 Controller 主动上报的 HCI Event，NimBLE 将这些 Event 放入工作队列等待被执行。

造成上述 Bug 的原因是我当前设置的 HCI Event 缓冲池数量为 **2**，也就是说整个系统里最多可以同时存在两个 HCI Event 包，而上图中连续收到 LE Meta Event (LE Enhanced Connection Complete) 和 LE Meta Event (LE Channel Selection Algorithm) 两个 HCI Event，而且并未被 NimBLE 协议栈及时处理。造成之后无法正常接收 Command Status Event，导致超时错误。

又由于 HM 组件内部 log 机制的不完善，当出现 Event 缓冲池不足时，会一直阻塞等待，而不会打印 log 提示用户。因此做了适当修改，下次出现该问题会有下述 log：

![](https://user-images.githubusercontent.com/45490946/132117392-41fe7eea-87ea-4def-b0e5-e12cadd6282d.png)

**Comment by Jackistang** [comment]
修复 commit： a58c2c65239b11a73f9c280c7752bd820a1495aa
